# Deployment file for platform service
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: platform-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: guptaharsh686/platformservice:latest
# --- is used to seperate the deployment from cluster ip config
---
#Creating a clusterip service used to establish communication between pods

apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: platformservice
  ports: 
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: platformgrpc
    protocol: TCP
    port: 666
    targetPort: 666



